/*
 *
 * Intelligences constants
 *
 */

export const RESET_INTELLIGENCES = 'DIA_UI/INTELLIGENCES/RESET_INTELLIGENCES';
export const REFRESH_INTELLIGENCES = 'DIA_UI/INTELLIGENCES/REFRESH_INTELLIGENCES';
export const REFRESH_INTELLIGENCES_SUCCESS = 'DIA_UI/INTELLIGENCES/REFRESH_INTELLIGENCES_SUCCESS';
export const REFRESH_INTELLIGENCES_FAIL = 'DIA_UI/INTELLIGENCES/REFRESH_INTELLIGENCES_FAIL';
