/*
 *
 * Producers constants
 *
 */

export const REFRESH_PRODUCERS = 'BITSKY_UI/Producers/REFRESH_PRODUCERS';
export const REFRESH_PRODUCERS_SUCCESS = 'BITSKY_UI/Producers/REFRESH_PRODUCERS_SUCCESS';
export const REFRESH_PRODUCERS_FAIL = 'BITSKY_UI/Producers/REFRESH_PRODUCERS_FAIL';
